version: '3.7'
services:
  test-prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/API-RestAssured
    command: ['gradle', 'clean', 'test', '-Denv=prod']
  test-local:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/API-RestAssured
    command: ['gradle', 'clean', 'test', '-Denv=local']